// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aacxlrdditiqsvygkwam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhY3hscmRkaXRpcXN2eWdrd2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjcxMTQsImV4cCI6MjA2MTk0MzExNH0.V17_lw3JwLNENTsXQNnkkniKUDIxbQbDgiki3qR9MHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);